name: Publish to NPM

on:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: npm-production
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: |
          cd n8n-nodes-icount
          npm ci

      - name: Build
        run: |
          cd n8n-nodes-icount
          npm run build

      - name: Publish to NPM
        run: |
          cd n8n-nodes-icount
          npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
